# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='email',
            new_name='content',
        ),
    ]
