# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0002_auto_20170223_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secret',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
