# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0003_auto_20170223_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likeduser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likedusers', to='dojosecrets.User'),
        ),
    ]
