# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0009_auto_20170223_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likeduser',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='likedusers', to='dojosecrets.User'),
        ),
    ]
