# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.User'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduled_users',
            field=models.ManyToManyField(default=0, related_name='schedules', to='travelbuddy.User'),
        ),
    ]
